import { Profile } from '../types/profile';
import { nanoid } from './nanoid';

export const DHANAM_PROFILE: Profile = {
  id: undefined,
  version: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  personal: {
    name: 'Dhanam Patel',
    email: 'dhanampatel2005@gmail.com',
    phone: '+918980045095',
    linkedin: 'https://linkedin.com/in/dhanampatel',
    github: 'https://github.com/dhanampatel',
    twitter: 'https://x.com/dhanampatel',
    portfolio: '',
    website: '',
    location: 'Vadodara, Gujarat, India',
    summary:
      'Computer Science undergraduate with hands-on experience in AI/ML, backend engineering, and full-stack development. Passionate about building impactful, production-ready solutions with a focus on machine learning pipelines, FastAPI services, and generative AI.',
    professionalSummary: {
      headline: 'Computer Science Undergraduate | AI/ML & Full-Stack Developer',
      yearsExperience: '2+ years',
      expertise: ['Machine Learning', 'FastAPI', 'Generative AI', 'Full-Stack Development'],
      objective: 'Seeking opportunities to build impactful AI-driven solutions at scale.',
      highlights: ['Built production-ready ML APIs', 'Interned at IBM and Shell', 'Developed empathetic conversational AI'],
      rawText: 'Computer Science undergraduate with hands-on experience in AI/ML, backend engineering, and full-stack development. Passionate about building impactful, production-ready solutions with a focus on machine learning pipelines, FastAPI services, and generative AI.',
    },
  },
  education: [
    {
      id: nanoid(),
      institution: 'Drs. Kiran & Pallavi Patel Global University',
      degree: 'Bachelor of Technology',
      field: 'Computer Science and Engineering',
      location: 'Vadodara, Gujarat',
      startDate: '2023-11',
      endDate: '2027-06',
      current: true,
      gpa: '',
      coursework: ['Data Structures', 'Algorithms', 'Machine Learning', 'Database Systems'],
      achievements: [],
      honors: '',
    },
    {
      id: nanoid(),
      institution: 'Phoenix Institute',
      degree: '12th Grade',
      field: 'Science',
      location: 'Vadodara, Gujarat',
      startDate: '2023-07',
      endDate: '2027-02',
      current: false,
      gpa: '',
      coursework: [],
      achievements: [],
      honors: '',
    },
    {
      id: nanoid(),
      institution: 'Avalon World School',
      degree: '10th Grade',
      field: '',
      location: 'Vadodara, Gujarat',
      startDate: '2023-05',
      endDate: '2027-06',
      current: false,
      gpa: '',
      coursework: [],
      achievements: [],
      honors: '',
    },
  ],
  experience: [
    {
      id: nanoid(),
      company: 'Edunet and Shell',
      role: 'Artificial Intelligence Intern (AI)',
      location: 'Remote',
      startDate: '2025-07',
      endDate: '2025-08',
      current: false,
      type: 'internship',
      responsibilities: [
        'Completed this internship on IBM Cloud through Edunet Foundation via the AICTE Internship Portal (Government of India).',
        'Gained hands-on experience with IBM Cloud services and AI tools.',
        'Worked on AI chatbot development and AutoAI projects for real-world problem solving.',
        'Engaged in structured learning through IBM SkillsBuild aligned with industry standards.',
        'Performed data analytics and visualization to derive actionable insights.',
        'Collaborated with mentors and industry professionals in an enterprise workflow environment.',
      ],
      achievements: [],
      technologies: ['IBM Cloud', 'AutoAI', 'IBM SkillsBuild', 'Data Analytics'],
      impact: '',
    },
    {
      id: nanoid(),
      company: 'Edunet and IBM',
      role: 'Artificial Intelligence & Cloud Technologies Intern',
      location: 'Remote',
      startDate: '2025-07',
      endDate: '2025-08',
      current: false,
      type: 'internship',
      responsibilities: [
        'Completed this internship at Shell through Edunet Foundation via the AICTE Internship Portal (Government of India).',
        'Developed end-to-end machine learning pipelines for structured datasets.',
        'Built production-ready FastAPI services for real-time model inference.',
        'Performed exploratory data analysis and feature engineering to improve model performance.',
        'Designed modular backend architecture for scalable experimentation and deployment.',
      ],
      achievements: [],
      technologies: ['FastAPI', 'Python', 'Machine Learning', 'Data Analysis', 'Feature Engineering'],
      impact: '',
    },
  ],
  projects: [
    {
      id: nanoid(),
      name: 'Dear AI',
      summary:
        'A compassionate conversational AI that acts as a trusted friend, helping users release emotional burdens with warm, non-clinical support using generative AI.',
      description:
        'Provides empathetic, concise responses with practical coping strategies, creating a safe, judgment-free space. Developed the backend with core AI and generative intelligence powering the conversations.',
      techStack: ['Python', 'Generative AI', 'LangChain', 'FastAPI'],
      challenges: 'Building context-aware emotional intelligence without clinical training data.',
      outcomes: 'Production-ready conversational AI with empathetic response generation.',
      metrics: '',
      repoUrl: 'https://github.com/dhanampatel/dear-ai',
      demoUrl: '',
      awards: '',
      businessOutcome: 'Mental wellness support accessible to users without clinical barriers.',
      startDate: '',
      endDate: '',
      current: false,
      featured: true,
    },
    {
      id: nanoid(),
      name: 'Insurance Premium Prediction API',
      summary:
        'A machine learning-powered REST API using FastAPI to predict insurance premiums based on user demographics and lifestyle factors.',
      description:
        'Focused on creating a reliable prediction pipeline with model deployment, input validation, and fast response times.',
      techStack: ['FastAPI', 'Python', 'Scikit-learn', 'Pandas', 'Docker'],
      challenges: 'Building reliable model inference with low latency and proper input validation.',
      outcomes: 'Production-ready prediction API with sub-100ms response times.',
      metrics: '',
      repoUrl: 'https://github.com/dhanampatel/insurance-premium-api',
      demoUrl: '',
      awards: '',
      businessOutcome: 'Automated premium estimation reducing manual underwriting effort.',
      startDate: '',
      endDate: '',
      current: false,
      featured: true,
    },
    {
      id: nanoid(),
      name: 'GHG-Prediction',
      summary:
        'A sustainability-focused analytics project exploring US supply chain GHG emissions using open data with EDA and visual insights.',
      description:
        'Built the end-to-end data pipeline, handled preprocessing, and created modular Jupyter notebooks for scalable analysis and future ML modeling.',
      techStack: ['Python', 'Pandas', 'Jupyter', 'Matplotlib', 'Scikit-learn'],
      challenges: 'Handling large-scale open datasets with inconsistent schemas.',
      outcomes: 'Cleaned datasets, EDA insights, and ML-ready pipeline identifying high-emission industries.',
      metrics: '',
      repoUrl: 'https://github.com/dhanampatel/ghg-prediction',
      demoUrl: '',
      awards: '',
      businessOutcome: 'Actionable sustainability intelligence for supply chain decision-makers.',
      startDate: '',
      endDate: '',
      current: false,
      featured: true,
    },
  ],
  skills: {
    languages: ['Python', 'JavaScript', 'C', 'C++', 'SQL'],
    frameworks: ['React.js', 'FastAPI', 'LangChain', 'Tailwind CSS', 'Pandas'],
    tools: ['GitHub', 'Docker', 'Linux', 'Nmap', 'Jupyter'],
    databases: ['PostgreSQL', 'Pinecone'],
    cloud: ['IBM Cloud'],
    soft: ['Problem Solving', 'Collaboration', 'Communication'],
    other: ['RAG', 'GenAI', 'Networking', 'Footprinting', 'HTML5', 'CSS'],
    categories: [],
  },
  certifications: [],
  publications: [],
  research: [],
  patents: [],
  volunteering: [],
  leadership: [],
  achievements: [],
  hackathons: [],
  awards: [],
  extracurricular: [],
  opensource: [],
  memberships: [],
  customSections: [],
};
