import { Profile } from '../types/profile';
import { nanoid } from './nanoid';

export const DEMO_PROFILE: Profile = {
  id: 'demo-123',
  version: 1,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  personal: {
    name: 'Alex Carter',
    email: 'alex.carter.demo@gmail.com',
    phone: '+1 234 567 8900',
    linkedin: 'https://linkedin.com/in/alexcarter',
    github: 'https://github.com/alexcarter',
    twitter: 'https://x.com/alexcarter',
    portfolio: 'https://alexcarter.dev',
    website: 'https://alexcarter.dev',
    location: 'San Francisco, CA',
    summary:
      'Passionate Software Engineer with 3+ years of experience building scalable web applications and microservices. Adept at collaborating in agile environments and delivering high-quality code. Proven track record of improving application performance and user experience.',
    professionalSummary: {
      headline: 'Software Engineer | Full-Stack Developer',
      yearsExperience: '3+ years',
      expertise: ['React', 'Node.js', 'TypeScript', 'Cloud Architecture'],
      objective: 'Seeking to leverage my expertise in scalable architectures to build innovative solutions.',
      highlights: ['Improved system latency by 40%', 'Led migration to microservices', 'Mentored junior developers'],
      rawText: 'Passionate Software Engineer with 3+ years of experience building scalable web applications and microservices. Adept at collaborating in agile environments and delivering high-quality code.',
    },
  },
  education: [
    {
      id: nanoid(),
      institution: 'University of California, Berkeley',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: '2016-08',
      endDate: '2020-05',
      current: false,
      gpa: '3.8',
      coursework: ['Data Structures', 'Operating Systems', 'Distributed Systems', 'Artificial Intelligence'],
      achievements: ['Dean\'s List', 'Hackathon Winner 2019'],
      honors: 'Cum Laude',
    }
  ],
  experience: [
    {
      id: nanoid(),
      company: 'Acme Corp',
      role: 'Software Engineer',
      location: 'San Francisco, CA',
      startDate: '2021-02',
      endDate: '',
      current: true,
      type: 'full-time',
      responsibilities: [
        'Designed and implemented scalable microservices using Node.js and TypeScript, reducing system latency by 40%.',
        'Led the frontend migration from Angular to React, improving developer velocity and application performance.',
        'Mentored 3 junior developers and established code review best practices.',
        'Collaborated with product managers to define technical requirements for new features.',
      ],
      achievements: ['Employee of the Month - Q3 2022'],
      technologies: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
      impact: 'Improved overall system reliability by 99.9%',
    },
    {
      id: nanoid(),
      company: 'TechStart Inc.',
      role: 'Software Engineering Intern',
      location: 'San Jose, CA',
      startDate: '2020-06',
      endDate: '2020-08',
      current: false,
      type: 'internship',
      responsibilities: [
        'Developed internal dashboard tools using React and Redux.',
        'Optimized database queries in MySQL, reducing report generation time by 20%.',
        'Wrote comprehensive unit and integration tests using Jest and Cypress.',
      ],
      achievements: [],
      technologies: ['React', 'Redux', 'MySQL', 'Jest'],
      impact: '',
    },
  ],
  projects: [
    {
      id: nanoid(),
      name: 'E-Commerce Microservices Platform',
      summary: 'A cloud-native e-commerce platform built with microservices architecture.',
      description: 'Developed a fully functional e-commerce backend with user authentication, product catalog, and payment processing.',
      techStack: ['Node.js', 'Express', 'MongoDB', 'Docker', 'Kubernetes'],
      challenges: 'Handling distributed transactions and maintaining data consistency.',
      outcomes: 'Successfully deployed a scalable platform capable of handling 10k+ concurrent users.',
      metrics: '',
      repoUrl: 'https://github.com/alexcarter/ecommerce-microservices',
      demoUrl: 'https://demo.alexcarter.dev/ecommerce',
      awards: '',
      businessOutcome: '',
      startDate: '2022-01',
      endDate: '2022-06',
      current: false,
      featured: true,
    },
    {
      id: nanoid(),
      name: 'Real-time Collaboration Workspace',
      summary: 'A web-based collaborative editor featuring real-time document synchronization.',
      description: 'Built a collaborative text editor using WebSockets and Operational Transformation.',
      techStack: ['React', 'Socket.io', 'Node.js', 'Redis'],
      challenges: 'Implementing conflict resolution for concurrent document edits.',
      outcomes: 'Created a seamless editing experience with sub-50ms latency.',
      metrics: '',
      repoUrl: 'https://github.com/alexcarter/collab-workspace',
      demoUrl: '',
      awards: '',
      businessOutcome: '',
      startDate: '2021-08',
      endDate: '2021-12',
      current: false,
      featured: true,
    }
  ],
  skills: {
    languages: ['JavaScript', 'TypeScript', 'Python', 'Go', 'HTML/CSS'],
    frameworks: ['React', 'Node.js', 'Express', 'Next.js', 'Tailwind CSS'],
    tools: ['Git', 'Docker', 'Kubernetes', 'Webpack', 'Jest'],
    databases: ['PostgreSQL', 'MongoDB', 'Redis'],
    cloud: ['AWS (EC2, S3, RDS)', 'Google Cloud Platform'],
    soft: ['Agile Methodologies', 'Team Leadership', 'Technical Communication'],
    other: ['RESTful APIs', 'GraphQL', 'CI/CD Pipelines'],
    categories: [],
  },
  certifications: [
    {
      id: nanoid(),
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      date: '2022-05',
      url: '',
    }
  ],
  publications: [],
  research: [],
  patents: [],
  volunteering: [],
  leadership: [],
  achievements: [],
  hackathons: [],
  awards: [],
  extracurricular: [],
  opensource: [],
  memberships: [],
  customSections: [],
};
